from pathlib import Path

BASE_DIR = Path('/home/mufaddal/PycharmProjects/datagen')
OUTPUT_DIR = BASE_DIR / 'output'
DEFAULT_CUSTOMERS = 1000
DEFAULT_PRODUCTS = 200
DEFAULT_ORDERS = 10000
DEFAULT_WAREHOUSES = 5
DEFAULT_INITIAL_STOCK_MIN = 200
DEFAULT_INITIAL_STOCK_MAX = 800
DEFAULT_REORDER_POINT = 60
DEFAULT_REORDER_QUANTITY = 250
SEED = 42
COUNTRY = 'India'
